development:
  adapter: mysql2
  encoding: utf8
  database: shout_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql2
  encoding: utf8
  database: shout_test
  pool: 5
  username: root
  password:

production:
  adapter: mysql2
  encoding: utf8
  database: shout_production
  pool: 5
  username: root
  password:
